from django.db import models

# Create your models here.
class Symbol(models.Model):
    symbol_id = models.IntegerField(primary_key=True, name="symbol_id")
    ticker = models.CharField()
    name_en = models.CharField()
    name_kr = models.CharField()

    class Meta:
        managed = False
        db_table = "Symbol"


class Upbit(models.Model):
    symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE, related_name="Upbits")
    timestamp = models.DateTimeField(auto_now_add=True)
    OPEN = models.FloatField()
    CLOSE = models.FloatField()
    HIGH = models.FloatField()
    LOW = models.FloatField()
    VOLUME = models.CharField(max_length=255)
    CMR = models.FloatField()
    UB = models.FloatField()
    LB = models.FloatField()
    MD = models.FloatField()
    WA = models.FloatField()
    EWA = models.FloatField()
    TMA = models.FloatField()
    EWMA = models.FloatField()
    HMA = models.FloatField()
    MA = models.FloatField()
    EMA = models.FloatField()
    SMA = models.FloatField()
    WMA = models.FloatField()
    VMA = models.FloatField()
    EMAD = models.FloatField()
    WMAD = models.FloatField()
    MAA = models.FloatField()
    MAG = models.FloatField()
    MAR = models.FloatField()
    MACD = models.FloatField()
    ATR = models.FloatField()
    BB = models.FloatField()
    RSI = models.FloatField()
    STIC = models.FloatField()
    SRSI = models.FloatField()
    WILLPR = models.FloatField()
    CCI = models.FloatField()
    AD = models.FloatField()
    ADO = models.FloatField()
    CB = models.FloatField()
    EP = models.FloatField()
    DMI = models.FloatField()
    AA = models.FloatField()
    LR = models.FloatField()
    MOTM = models.FloatField()
    EM = models.FloatField()
    WM = models.FloatField()
    MAM = models.FloatField()
    ROC = models.FloatField()
    ROCR = models.FloatField()
    ROCP = models.FloatField()
    TEMA = models.FloatField()
    ROCA = models.FloatField()
    PPSR = models.FloatField()
    FR = models.FloatField()
    FP = models.FloatField()
    PDC = models.FloatField()
    EMAC = models.FloatField()
    WMAC = models.FloatField()
    KAMA = models.FloatField()
    CMO = models.FloatField()
    KVO = models.FloatField()
    EI = models.FloatField()
    QSI = models.FloatField()
    STC = models.FloatField()
    UO = models.FloatField()
    DC = models.FloatField()
    MCDHST = models.FloatField()
    IHH = models.FloatField()
    OBV = models.FloatField()
    CMF = models.FloatField()
    AP = models.FloatField()
    EA = models.FloatField()
    ES = models.FloatField()
    EMAROC = models.FloatField()
    KSTO = models.FloatField()
    KER = models.FloatField()
    LRI = models.FloatField()
    LRS = models.FloatField()
    SD = models.FloatField()
    SND = models.FloatField()
    VAR = models.FloatField()
    BETA = models.FloatField()
    COV = models.FloatField()
    KURTS = models.FloatField()
    SKNS = models.FloatField()
    STEM = models.FloatField()
    TTEST = models.FloatField()
    VR = models.FloatField()

    class Meta:
        managed = False
        db_table = "Upbit"
