from django.db import models

# Create your models here.
class Symbol(models.Model):
    symbol_id = models.IntegerField(primary_key=True, name="symbol_id")
    ticker = models.CharField(max_length=255)
    name_en = models.CharField(max_length=255)
    name_kr = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = "Symbol"


class Upbit(models.Model):
    symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE, related_name="Upbits")
    timestamp = models.DateTimeField(auto_now_add=True)
    OPEN = models.FloatField()
    CLOSE = models.FloatField()
    HIGH = models.FloatField()
    LOW = models.FloatField()
    VOLUME = models.CharField(max_length=255)
    CMR = models.FloatField()
    UB = models.FloatField()
    LB = models.FloatField()
    MD = models.FloatField()
    WA = models.FloatField()
    EWA = models.FloatField()
    TMA = models.FloatField()
    EWMA = models.FloatField()
    HMA = models.FloatField()
    MA = models.FloatField()
    EMA = models.FloatField()
    SMA = models.FloatField()
    WMA = models.FloatField()
    VMA = models.FloatField()
    EMAD = models.FloatField()
    WMAD = models.FloatField()
    MAA = models.FloatField()
    MAG = models.FloatField()
    MAR = models.FloatField()
    MACD = models.FloatField()
    ATR = models.FloatField()
    BB = models.FloatField()
    RSI = models.FloatField()
    STIC = models.FloatField()
    SRSI = models.FloatField()
    WILLPR = models.FloatField()
    CCI = models.FloatField()
    AD = models.FloatField()
    ADO = models.FloatField()
    CB = models.FloatField()
    EP = models.FloatField()
    DMI = models.FloatField()
    AA = models.FloatField()
    LR = models.FloatField()
    MOTM = models.FloatField()
    EM = models.FloatField()
    WM = models.FloatField()
    MAM = models.FloatField()
    ROC = models.FloatField()
    ROCR = models.FloatField()
    ROCP = models.FloatField()
    TEMA = models.FloatField()
    ROCA = models.FloatField()
    PPSR = models.FloatField()
    FR = models.FloatField()
    FP = models.FloatField()
    PDC = models.FloatField()
    EMAC = models.FloatField()
    WMAC = models.FloatField()
    KAMA = models.FloatField()
    CMO = models.FloatField()
    KVO = models.FloatField()
    EI = models.FloatField()
    QSI = models.FloatField()
    STC = models.FloatField()
    UO = models.FloatField()
    DC = models.FloatField()
    MCDHST = models.FloatField()
    IHH = models.FloatField()
    OBV = models.FloatField()
    CMF = models.FloatField()
    AP = models.FloatField()
    EA = models.FloatField()
    ES = models.FloatField()
    EMAROC = models.FloatField()
    KSTO = models.FloatField()
    KER = models.FloatField()
    LRI = models.FloatField()
    LRS = models.FloatField()
    SD = models.FloatField()
    SND = models.FloatField()
    VAR = models.FloatField()
    BETA = models.FloatField()
    COV = models.FloatField()
    KURTS = models.FloatField()
    SKNS = models.FloatField()
    STEM = models.FloatField()
    TTEST = models.FloatField()
    VR = models.FloatField()

    class Meta:
        managed = False
        db_table = "Upbit"


class SymbolTest(models.Model):
    symbol_id = models.IntegerField(primary_key=True, name="symbol_id")
    ticker = models.CharField(max_length=255)
    name_en = models.CharField(max_length=255)
    name_kr = models.CharField(max_length=255)


class ScreeningTest(models.Model):
    symbol = models.ForeignKey(
        SymbolTest, on_delete=models.CASCADE, related_name="Tests"
    )
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    OPEN = models.FloatField(null=True)
    HIGH = models.FloatField(null=True)
    LOW = models.FloatField(null=True)
    CLOSE = models.FloatField(null=True)
    VOLUME = models.FloatField(null=True)
    MA = models.FloatField(null=True)
    EMA = models.FloatField(null=True)
    SMA = models.FloatField(null=True)
    WMA = models.FloatField(null=True)
    VMA = models.FloatField(null=True)
    EMAD = models.FloatField(null=True)
    WMAD = models.FloatField(null=True)
    CMA = models.FloatField(null=True)
    BB_UPPER = models.FloatField(null=True)
    BB_LOWER = models.FloatField(null=True)
    MD = models.FloatField(null=True)
    WAVG = models.FloatField(null=True)
    EWAVG = models.FloatField(null=True)
    TRIMA = models.FloatField(null=True)
    EWMA = models.FloatField(null=True)
    HMA = models.FloatField(null=True)
    MAA = models.FloatField(null=True)
    MAG = models.FloatField(null=True)
    MAR = models.FloatField(null=True)
    MACD = models.FloatField(null=True)
    MACD_SIGNAL = models.FloatField(null=True)
    ATR = models.FloatField(null=True)
    RSI = models.FloatField(null=True)
    SLOWK = models.FloatField(null=True)
    SLOWD = models.FloatField(null=True)
    FASTK = models.FloatField(null=True)
    FASTD = models.FloatField(null=True)
    WILLIAMS = models.FloatField(null=True)
    CCI = models.FloatField(null=True)
    AD = models.FloatField(null=True)
    ADOSC = models.FloatField(null=True)
    EP = models.FloatField(null=True)
    DMI = models.FloatField(null=True)
    AA = models.FloatField(null=True)
    LR = models.FloatField(null=True)
    MOTM = models.FloatField(null=True)
    EM = models.FloatField(null=True)
    WM = models.FloatField(null=True)
    MOM = models.FloatField(null=True)
    ROC = models.FloatField(null=True)
    ROCR = models.FloatField(null=True)
    ROCP = models.FloatField(null=True)
    TEMA = models.FloatField(null=True)
    ROCA = models.FloatField(null=True)
    PIVOT = models.FloatField(null=True)
    R2 = models.FloatField(null=True)
    R1 = models.FloatField(null=True)
    S1 = models.FloatField(null=True)
    S2 = models.FloatField(null=True)
    PDCUP = models.FloatField(null=True)
    PDCDN = models.FloatField(null=True)
    EMAC = models.FloatField(null=True)
    WMAC = models.FloatField(null=True)
    KAMA = models.FloatField(null=True)
    CMO = models.FloatField(null=True)
    OBV = models.FloatField(null=True)
    KVO = models.FloatField(null=True)
    ECI = models.FloatField(null=True)
    EMVA = models.FloatField(null=True)
    QSTICK = models.FloatField(null=True)
    STC = models.FloatField(null=True)
    ULTOSC = models.FloatField(null=True)
    DCUP = models.FloatField(null=True)
    DCDN = models.FloatField(null=True)
    DCMI = models.FloatField(null=True)
    MCDHST = models.FloatField(null=True)
    CMF = models.FloatField(null=True)
    AP = models.FloatField(null=True)
    ES = models.FloatField(null=True)
    EMAROC = models.FloatField(null=True)
    KSTO = models.FloatField(null=True)
    KER = models.FloatField(null=True)
    LRI = models.FloatField(null=True)
    LRS = models.FloatField(null=True)
    SD = models.FloatField(null=True)
    SND = models.FloatField(null=True)
    VAR = models.FloatField(null=True)
    COV = models.FloatField(null=True)
    KURTS = models.FloatField(null=True)
    SKNS = models.FloatField(null=True)
    STEM = models.FloatField(null=True)
    VR = models.FloatField(null=True)
