# Generated by Django 4.1.2 on 2023-03-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_kr", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("tradingview_market_code", models.CharField(max_length=100)),
                ("tradingview_upbit_code", models.CharField(max_length=100)),
                ("upbit_stock_code", models.CharField(max_length=100)),
                ("unable_marketwidget", models.BooleanField()),
            ],
        ),
    ]
