CREATE TABLE `SYMBOLS` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT '심볼 순번',
  `TICKER` varchar(255) NOT NULL,
  `NAME_EN` varchar(255) DEFAULT NULL,
  `NAME_KR` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3965 DEFAULT CHARSET=utf8 COMMENT='심볼 테이블';