CREATE TABLE `upbit_spot_krw_240m` (
  `DATE` date NOT NULL COMMENT '일시',
  `OPEN` float unsigned NOT NULL COMMENT '시가',
  `HIGH` float unsigned NOT NULL COMMENT '고가',
  `LOW` float unsigned NOT NULL COMMENT '저가',
  `CLOSE` float unsigned NOT NULL COMMENT '종가',
  `VOLUME` varchar(255) NOT NULL COMMENT '거래량',
  `ID` int unsigned DEFAULT NULL COMMENT '심볼 순번',
  `TICKER` varchar(255) NOT NULL,
  `MA` float DEFAULT NULL,
  `EMA` float DEFAULT NULL,
  `SMA` float DEFAULT NULL,
  `WMA` float DEFAULT NULL,
  `VMA` float DEFAULT NULL,
  `EMAD` float DEFAULT NULL,
  `WMAD` float DEFAULT NULL,
  `CMA` float DEFAULT NULL,
  `BB_UPPER` float DEFAULT NULL,
  `BB_LOWER` float DEFAULT NULL,
  `MD` float DEFAULT NULL,
  `WAVG` float DEFAULT NULL,
  `EWAVG` float DEFAULT NULL,
  `TRIMA` float DEFAULT NULL,
  `EWMA` float DEFAULT NULL,
  `HMA` float DEFAULT NULL,
  `MAA` float DEFAULT NULL,
  `MAG` float DEFAULT NULL,
  `MAR` float DEFAULT NULL,
  `MACD` float DEFAULT NULL,
  `MACD_SIGNAL` float DEFAULT NULL,
  `ATR` float DEFAULT NULL,
  `RSI` float DEFAULT NULL,
  `SLOWK` float DEFAULT NULL,
  `SLOWD` float DEFAULT NULL,
  `FASTK` float DEFAULT NULL,
  `FASTD` float DEFAULT NULL,
  `WILLIAMS %R` float DEFAULT NULL,
  `CCI` float DEFAULT NULL,
  `AD` float DEFAULT NULL,
  `ADOSC` float DEFAULT NULL,
  `EP` float DEFAULT NULL,
  `DMI` float DEFAULT NULL,
  `AA` float DEFAULT NULL,
  `LR` float DEFAULT NULL,
  `MOTM` float DEFAULT NULL,
  `EM` float DEFAULT NULL,
  `WM` float DEFAULT NULL,
  `MOM` float DEFAULT NULL,
  `ROC` float DEFAULT NULL,
  `ROCR` float DEFAULT NULL,
  `ROCP` float DEFAULT NULL,
  `TEMA` float DEFAULT NULL,
  `ROCA` float DEFAULT NULL,
  `PIVOT` float DEFAULT NULL,
  `R2` float DEFAULT NULL,
  `R1` float DEFAULT NULL,
  `S1` float DEFAULT NULL,
  `S2` float DEFAULT NULL,
  `PDCUP` float DEFAULT NULL,
  `PDCDN` float DEFAULT NULL,
  `EMAC` float DEFAULT NULL,
  `WMAC` float DEFAULT NULL,
  `KAMA` float DEFAULT NULL,
  `CMO` float DEFAULT NULL,
  `OBV` float DEFAULT NULL,
  `KVO` float DEFAULT NULL,
  `ECI` float DEFAULT NULL,
  `EMVA` float DEFAULT NULL,
  `QSTICK` float DEFAULT NULL,
  `STC` float DEFAULT NULL,
  `ULTOSC` float DEFAULT NULL,
  `DCUP` float DEFAULT NULL,
  `DCDN` float DEFAULT NULL,
  `DCMI` float DEFAULT NULL,
  `MCDHST` float DEFAULT NULL,
  `CMF` float DEFAULT NULL,
  `AP` float DEFAULT NULL,
  `ES` float DEFAULT NULL,
  `EMAROC` float DEFAULT NULL,
  `KSTO` float DEFAULT NULL,
  `KER` float DEFAULT NULL,
  `LRI` float DEFAULT NULL,
  `LRS` float DEFAULT NULL,
  `SD` float DEFAULT NULL,
  `SND` float DEFAULT NULL,
  `VAR` float DEFAULT NULL,
  `COV` float DEFAULT NULL,
  `KURTS` float DEFAULT NULL,
  `SKNS` float DEFAULT NULL,
  `STEM` float DEFAULT NULL,
  `VR` float DEFAULT NULL,
  KEY `FK_SYMBOLS_TO_UPBIT_SPOT_KRW_240M` (`ID`),
  CONSTRAINT `FK_SYMBOLS_TO_UPBIT_SPOT_KRW_240M` FOREIGN KEY (`ID`) REFERENCES `symbols` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='UPBIT_SPOT_KRW_240M'
