# Generated by Django 4.1.2 on 2023-06-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price1d",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="price240m",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="price30m",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="price60m",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
