# Generated by Django 4.1.5 on 2023-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="alarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filter",
            name="expression",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="filter",
            name="time",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="indicator",
            field=models.CharField(default="", max_length=100),
        ),
    ]
