# Generated by Django 4.1.5 on 2023-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0002_filter_alarm_filter_expression_filter_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="indicator",
            field=models.CharField(max_length=100),
        ),
    ]
