# Generated by Django 4.1.2 on 2023-05-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0003_alter_setting_indicator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Previous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_data", models.CharField(max_length=1000)),
                (
                    "filter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous",
                        to="filter.filter",
                    ),
                ),
            ],
        ),
    ]
