# Generated by Django 4.1.2 on 2023-06-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0004_previous"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="filter",
            table="Filter",
        ),
        migrations.AlterModelTable(
            name="previous",
            table="Previous",
        ),
        migrations.AlterModelTable(
            name="setting",
            table="Setting",
        ),
    ]
