# Generated by Django 4.1.2 on 2023-06-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alarm",
            table="Alarm",
        ),
    ]
