# Generated by Django 4.1.2 on 2023-05-31 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0002_alter_alarm_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 31, 3, 30, 41, 992475, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
