# Generated by Django 4.1.5 on 2023-03-05 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_attention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attention",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
