# Generated by Django 4.1.2 on 2023-06-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_attention_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="attention",
            table="Attention",
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
