# Generated by Django 4.0 on 2023-06-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_groups_alter_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegram",
            name="id",
        ),
        migrations.AlterField(
            model_name="telegram",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="users.user",
            ),
        ),
    ]
